version: '3.6'
services:
  php-fpm-7.0:
    build:
      context: ./php7.0/
    ports:
      - "9000:9000"
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    volumes:
      - ${HOST_APP_CODE_PATH}:/data/www:rw  #本地目录挂载到镜像中
      - ./php7.0/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ./php7.0/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
#      - /data/docker/home:/root:rw

    restart: always
    command: php-fpm

  php-fpm-7.3:
    build:
      context: ./php7.3/
    ports:
      - "9001:9001"
    env_file:
      - .env
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    volumes:
      - ${HOST_APP_CODE_PATH}:/data/www:rw # 本地目录挂载到镜像中
      - ./php7.3/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ./php7.3/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
#      - /data/docker/home:/root:rw

    restart: always
    command: php-fpm

  nginx:
    build:
      context: ./nginx
    env_file:
      - .env
    depends_on:
      - php-fpm-7.0
    links:
      - php-fpm-7.0:php-fpm-7.0
    volumes:
      - ${HOST_APP_CODE_PATH}:/data/www:rw # 本地目录挂载到镜像中
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'

  mysql-db:
     build: ./mysql
     ports:
       - "3306:3306"
     volumes:
       - ../data/mysql:/var/lib/mysql:rw
       - ../logs/mysql:/var/lib/mysql-logs:rw
       - ./mysql/conf.d:/etc/mysql/conf.d:ro
     environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: zphaldb
       MYSQL_USER: zphal
       MYSQL_PASSWORD: zphal123
     restart: always
     command: "--character-set-server=utf8"

  redis-db:
     build: ./redis
     ports:
       - "6379:6379"
     volumes:
       - ../data/redis:/data
     restart: always